[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[program:fastapi]
command=/usr/local/bin/gunicorn -c /etc/dingo-bear/gunicorn.py dingo_command.main:app
directory=/opt/dingo-aurora
autostart=true
autorestart=true
stdout_logfile=/var/log/dingo-bear/dingo-bear.log
stderr_logfile=/var/log/dingo-bear/dingo-bear.err

[program:celery]
command=celery -A dingo_command.celery_api.workers worker -n dingo-bear@%(host_node_name)s -Q dingo-bear --loglevel=info --pool=threads --concurrency=16
directory=/opt/dingo-aurora
autostart=true
autorestart=true
stdout_logfile=/var/log/dingo-bear/celery.log
stderr_logfile=/var/log/dingo-bear/celery-err.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/dingo-bear/nginx-access.log
stderr_logfile=/var/log/dingo-bear/nginx-error.log

[program:flower]
command=celery -A dingo_command.celery_api.workers flower --port=5555
directory=/opt/dingo-aurora
stdout_logfile=/var/log/dingo-bear/flower.log
stderr_logfile=/var/log/dingo-bear/flower-err.log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
prompt=dingoops-supervisor
