---
- name: restart ovs-doca-db
  systemd:
    name: ovs-doca-db
    state: restarted
    daemon_reload: true

- name: restart ovs-doca-vswitchd
  systemd:
    name: ovs-doca-vswitchd
    state: restarted
    daemon_reload: true
