---
dingo_command_services:
  dingo-command:
    container_name: dingo-command
    group: dingo-command
    enabled: true
    image: "{{ dingo_command_image_full }}"
    volumes: "{{ dingo_command_default_volumes + dingo_command_extra_volumes }}"
    dimensions: "{{ dingo_command_dimensions }}"
    healthcheck: "{{ dingo_command_healthcheck }}"
    haproxy:
      dingo-command:
        enabled: "{{ enable_dingo_command }}"
        mode: "http"
        external: false
        port: "{{ dingo_command_port }}"
        listen_port: "{{ dingo_command_listen_port }}"
        tls_backend: "{{ dingo_command_enable_tls_backend }}"
        backend_http_extra:
          - "option httpchk GET /docs"
      dingo_command_external:
        enabled: "{{ enable_dingo_command }}"
        mode: "http"
        external: true
        external_fqdn: "{{ dingo_command_external_fqdn }}"
        port: "{{ dingo_command_port }}"
        listen_port: "{{ dingo_command_listen_port }}"
        tls_backend: "{{ dingo_command_enable_tls_backend }}"
        backend_http_extra:
          - "option httpchk GET /docs"

dingo_command_database_address: "{{ database_address | put_address_in_context('url') }}:{{ database_port }}"
dingo_command_tag: "{{ openstack_tag }}"
#optional ceph nfs local
dingo_command_workerdir_storage_type: "local"
dingo_command_workerdir_storage_local_path: "/var/lib/dingo-command"

dingo_command_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/dingo-command"
dingo_command_image_full: "{{ dingo_command_image }}:{{ dingo_command_tag }}"
dingo_command_config_directory: "/etc/dingo-command"
dingo_command_default_volumes:
  - "{{ node_config_directory }}/dingo-command/:{{ dingo_command_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "/var/log/kolla/dingo-command/:/var/log/dingo-command/"
  - "{{ dingo_command_workerdir_storage_local_path }}/:/var/lib/dingo-command/"

dingo_command_extra_volumes: "{{ default_extra_volumes }}"
dingo_command_dimensions: "{{ default_container_dimensions }}"

dingo_command_enable_healthchecks: "{{ enable_container_healthchecks }}"
dingo_command_healthcheck_interval: "{{ default_container_healthcheck_interval }}"
dingo_command_healthcheck_retries: "{{ default_container_healthcheck_retries }}"
dingo_command_healthcheck_start_period: "{{ default_container_healthcheck_start_period }}"
dingo_command_healthcheck_test: ["CMD-SHELL", "curl --max-time 10 http://{{ api_interface_address | put_address_in_context('url') }}:{{ dingo_command_listen_port }}/docs"]
dingo_command_healthcheck_timeout: "{{ default_container_healthcheck_timeout }}"
dingo_command_healthcheck:
  interval: "{{ dingo_command_healthcheck_interval }}"
  retries: "{{ dingo_command_healthcheck_retries }}"
  start_period: "{{ dingo_command_healthcheck_start_period }}"
  test: "{% if dingo_command_enable_healthchecks | bool %}{{ dingo_command_healthcheck_test }}{% else %}NONE{% endif %}"
  timeout: "{{ dingo_command_healthcheck_timeout }}"

openstack_dingo_command_auth: "{{ openstack_auth }}"
dingo_command_port: 8887
dingo_command_public_port: 8887
dingo_command_listen_port: "{{ dingo_command_port }}"
####################
# OpenStack
####################
dingo_command_internal_base_endpoint: "{{ dingo_command_internal_fqdn | kolla_url(internal_protocol, dingo_command_port) }}"
dingo_command_public_base_endpoint: "{{ dingo_command_external_fqdn | kolla_url(public_protocol, dingo_command_public_port) }}"

dingo_command_keystone_user: dingo-command
dingo_command_keystone_password: Zetyun.123
dingo_command_ks_services:
  - name: "dingo-command"
    type: "panel"
    description: "OpenStack assets Service"
    endpoints:
      - {'interface': 'internal', 'url': '{{ dingo_command_internal_base_endpoint }}'}
      - {'interface': 'public', 'url': '{{ dingo_command_public_base_endpoint }}'}

dingo_command_ks_users:
  - project: "service"
    user: "{{ dingo_command_keystone_user }}"
    password: "{{ dingo_command_keystone_password }}"
    role: "admin"

####################
# Database
####################
dingo_command_database_name: "dingoops"
dingo_command_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}dingoops{% endif %}"
dingo_command_database_address: "{{ database_address | put_address_in_context('url') }}:{{ database_port }}"
dingo_command_database_password: Zetyun.123
####################
# Database sharding
####################
dingo_command_database_shard_root_user: "{% if enable_proxysql | bool %}root_shard_{{ dingo_command_database_shard_id }}{% else %}{{ database_user }}{% endif %}"
dingo_command_database_shard_id: "{{ mariadb_default_database_shard_id | int }}"
dingo_command_database_shard:
  users:
    - user: "{{ dingo_command_database_user }}"
      password: "{{ dingo_command_database_password }}"
  rules:
    - schema: "{{ dingo_command_database_name }}"
      shard_id: "{{ dingo_command_database_shard_id }}"


####################
# TLS
####################
dingo_command_enable_tls_backend: "{{ kolla_enable_tls_backend }}"

ceph_keyring_content: "AQDGGBxo1+6EAxAAPtO87F7AtDfsmQVmVYLVbw=="
dingo_command_ceph_fsid: "7e4c0eda-02e0-11ef-bedf-e4434b2ce110"
dingo_command_ceph_mon_hosts:
  - "[v2:10.220.8.46:3300/0,v1:10.220.8.46:6789/0]"
  - "[v2:10.220.8.47:3300/0,v1:10.220.8.47:6789/0]"
  - "[v2:10.220.8.48:3300/0,v1:10.220.8.48:6789/0]"
  - "[v2:10.220.8.45:3300/0,v1:10.220.8.45:6789/0]"
  - "[v2:10.220.8.44:3300/0,v1:10.220.8.44:6789/0]"
dingo_command_ceph_mon_name: "sd-ceph01"
dingo_command_ceph_public_network: "10.220.8.0/22"

dingo_command_ceph_mon_addresses: "10.220.8.46:6789,10.220.8.47:6789,10.220.8.48:6789"
dingo_command_ceph_client_name: "dingoops-hdd-fs"
dingo_command_ceph_mds_namespace: "dingoops-cephfs-hdd"
dingo_command_ceph_mount_path: "{{ dingo_command_workerdir_storage_local_path }}"
dingo_command_ceph_fs_name: "/dingoops-test"

task_timeout: 7500
soft_task_timeout: 7200