---
- name: Ensuring /var/log/dingo-command directory exists
  file:
    path: "/var/log/kolla/dingo-command"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  with_dict: "{{ dingo_command_services | select_services_enabled_and_mapped_to_host }}"
- name: Ensuring /var/lib/dingo-command directory exists
  file:
    path: "/var/lib/dingo-command"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  with_dict: "{{ dingo_command_services | select_services_enabled_and_mapped_to_host }}"
  
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  with_dict: "{{ dingo_command_services | select_services_enabled_and_mapped_to_host }}"

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool or dingo_command_enable_tls_backend | bool

- name: Copying over dingo-command.conf
  vars:
    dingo_command: "{{ dingo_command_services['dingo-command'] }}"
  template:
    src: "{{ role_path }}/templates/dingo-command.conf.j2"
    dest: "{{ node_config_directory }}/dingo-command/dingo-command.conf"
    mode: "0660"
  become: true
  when:
    - dingo_command.enabled | bool
  notify:
    - Restart dingo-command container

- name: Copying over supervisord.conf
  vars:
    dingo_command: "{{ dingo_command_services['dingo-command'] }}"
  template:
    src: "{{ role_path }}/templates/supervisord.conf"
    dest: "{{ node_config_directory }}/dingo-command/supervisord.conf"
    mode: "0660"
  become: true
  when:
    - dingo_command.enabled | bool
  notify:
    - Restart dingo-command container

- name: Copying over gunicorn.py
  vars:
    dingo_command: "{{ dingo_command_services['dingo-command'] }}"
  template:
    src: "{{ role_path }}/templates/gunicorn.py"
    dest: "{{ node_config_directory }}/dingo-command/gunicorn.py"
    mode: "0660"
  become: true
  when:
    - dingo_command.enabled | bool
  notify:
    - Restart dingo-command container

- name: Copying over .terraformrc
  vars:
    dingo_command: "{{ dingo_command_services['dingo-command'] }}"
  template:
    src: "{{ role_path }}/templates/.terraformrc"
    dest: "/root/.terraformrc"
    mode: "0660"
  become: true
  when:
    - dingo_command.enabled | bool
  notify:
    - Restart dingo-command container

- include_tasks: "ceph.yml"

- name: Ensuring terraform-cache directory exists
  file:
    path: "/var/lib/dingo-command/terraform-cache"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  with_dict: "{{ dingo_command_services | select_services_enabled_and_mapped_to_host }}"

- name: Copy dingo.com terraform providers
  copy:
    src: "{{ role_path }}/templates/dingo.com"
    dest: "/var/lib/dingo-command/terraform-cache/"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
    directory_mode: "0770"
  become: true
  when:
    - dingo_command_services['dingo-command'].enabled | bool
  notify:
    - Restart dingo-command container

- name: Copy registry.terraform.io terraform providers
  copy:
    src: "{{ role_path }}/templates/registry.terraform.io"
    dest: "/var/lib/dingo-command/terraform-cache/"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
    directory_mode: "0770"
  become: true
  when:
    - dingo_command_services['dingo-command'].enabled | bool
  notify:
    - Restart dingo-command container