---
- name: "Configure loadbalancer for {{ project_name }}"
  import_role:
    name: loadbalancer-config
  vars:
    project_services: "{{ dingo_command_services }}"
  tags: always

- name: "Configure loadbalancer for dingo-bear"
  import_role:
    name: loadbalancer-config
  vars:
    project_services: "{{ dingo_bear_services }}"
  tags: always