---
- include_tasks: clone.yml
  when: manila_dev_mode | bool

- include_tasks: register.yml
  when: inventory_hostname in groups['manila-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['manila-api'][0] or
        inventory_hostname in groups['manila-data'][0] or
        inventory_hostname in groups['manila-share'][0] or
        inventory_hostname in groups['manila-scheduler'][0]

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['manila-api'][0]

- name: Flush handlers
  meta: flush_handlers

- include_tasks: config.yml
  when: inventory_hostname not in groups['manila-api'][0] or
        inventory_hostname not in groups['manila-data'][0] or
        inventory_hostname not in groups['manila-share'][0] or
        inventory_hostname not in groups['manila-scheduler'][0]

- include_tasks: bootstrap.yml
  when: inventory_hostname not in groups['manila-api'][0]

- name: Flush handlers
  meta: flush_handlers

- include_tasks: fix_cephfs_owner.yml
  when:
    - not enable_ceph | bool or enable_ceph_mds | bool
    - enable_manila_backend_cephfs_native | bool
    - inventory_hostname in groups['manila-share']
